### ISSUE TITLE
Issues with Neural(Meta)Group

### ISSUE THREAD

**Issue by Silmathoron** [tfardet/NNGT#142] opened 2020-11-26 15:38 UTC
In NNGT 2.2, default ``NeuralGroup`` should be excitatory.
There is also an issue with ``MetaGroup`` name attribute (e.g. using ``create_metagroup`` function).

**Comment by tfardet** [comment] 2021-06-21 08:31
NeuralGroup default fixed by 1a95fe3843c3c33d8e62bb92bacb76b13fd27adc, could not reproduce the metagroup issue

**Closed by tfardet** 2021-06-21 08:31 UTC
Labels: bug
